- name: Install OpsCenter
  shell: sudo apt-get install opscenter

- name: Start OpsCenter
  shell: sudo service opscenterd start

- name: Create Agent Folders
  shell: >
    sudo mkdir -p /usr/share/datastax-agent/dse-node1 && 
    sudo mkdir -p /usr/share/datastax-agent/dse-node2 && 
    sudo mkdir -p /usr/share/datastax-agent/dse-node3

- name: Install Node1 Agent
  shell: >
    cd /usr/share/datastax-agent/dse-node1 && 
    sudo curl --user jonathan_reiter@mcafee.com:1CoolDude -L http://downloads.datastax.com/enterprise/datastax-agent-6.1.tar.gz | sudo tar xz

- name: Install Node2 Agent
  shell: >
    cd /usr/share/datastax-agent/dse-node2 && 
    sudo curl --user jonathan_reiter@mcafee.com:1CoolDude -L http://downloads.datastax.com/enterprise/datastax-agent-6.1.tar.gz | sudo tar xz

- name: Install Node3 Agent
  shell: > 
    cd /usr/share/datastax-agent/dse-node3 && 
    sudo curl --user jonathan_reiter@mcafee.com:1CoolDude -L http://downloads.datastax.com/enterprise/datastax-agent-6.1.tar.gz | sudo tar xz

- name: Configure Node1 Agent
  copy: 
    content: "stomp_interface: 127.0.0.1\nagent_rpc_interface: 127.0.0.2\njmx_port: 7299" 
    dest: /usr/share/datastax-agent/dse-node1/datastax-agent-6.1.1/conf/address.yaml

- name: Configure Node2 Agent
  copy: 
    content: "stomp_interface: 127.0.0.1\nagent_rpc_interface: 127.0.0.3\njmx_port: 7399" 
    dest: /usr/share/datastax-agent/dse-node2/datastax-agent-6.1.1/conf/address.yaml

- name: Configure Node3 Agent
  copy: 
    content: "stomp_interface: 127.0.0.1\nagent_rpc_interface: 127.0.0.4\njmx_port: 7499"
    dest: /usr/share/datastax-agent/dse-node3/datastax-agent-6.1.1/conf/address.yaml
