- name: Define ip aliases
  shell: >
    sudo ifconfig lo:0 127.0.0.2 netmask 255.0.0.0 up && 
    sudo ifconfig lo:1 127.0.0.3 netmask 255.0.0.0 up && 
    sudo ifconfig lo:2 127.0.0.4 netmask 255.0.0.0 up &&
    sudo ifconfig lo:3 127.0.0.5 netmask 255.0.0.0 up

- name: Add hosts to hosts file
  shell: >
    sudo sed -i "2i127.0.0.2 node1 dse-node1" /etc/hosts && 
    sudo sed -i "2i127.0.0.3 node2 dse-node2" /etc/hosts && 
    sudo sed -i "2i127.0.0.4 node3 dse-node3" /etc/hosts &&
    sudo sed -i "2i127.0.0.5 grakn grakn" /etc/hosts

- name: Add nodes 
  shell: > 
    sudo dse add-node --node-id node1 --cluster Cassandra --listen-address 127.0.0.2 --rpc-address 127.0.0.2 --seeds 127.0.0.2 && 
    sudo dse add-node --node-id node2 --cluster Cassandra --listen-address 127.0.0.3 --rpc-address 127.0.0.3 --seeds 127.0.0.2 && 
    sudo dse add-node --node-id node3 --cluster NewCluster --listen-address 127.0.0.4 --rpc-address 127.0.0.4 --seeds 127.0.0.4

- name: Configure Node1
  replace:
    path: /etc/dse-node1/cassandra/cassandra-env.sh
    regexp: 'JMX_PORT="7199"'
    replace: 'JMX_PORT="7299"\nJVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=127.0.0.2"'

- name: Configure Node2
  replace:
    path: /etc/dse-node2/cassandra/cassandra-env.sh
    regexp: 'JMX_PORT="7199"'
    replace: 'JMX_PORT="7399"\nJVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=127.0.0.3"'

- name: Configure Node3
  replace:
    path: /etc/dse-node3/cassandra/cassandra-env.sh
    regexp: 'JMX_PORT="7199"'
    replace: 'JMX_PORT="7499"\nJVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname=127.0.0.4"'

- name: Start nodes
  shell: >
    sudo service dse-node1 start && 
    sudo service dse-node2 start && 
    sudo service dse-node3 start
