- name: Updating machine cache
  apt: update_cache=yes

- name: Installing dependencies
  apt: pkg={{ item }} state=installed update-cache=yes
  with_items:
  - curl
  - libssl0.9.8
  - libjna-java
  - sysstat
  - python-software-properties
  - git
  - maven
  - nodejs
  - npm
