- name: Preparing for Java installation
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: Installing Oracle Java JDK
  shell: DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes install oracle-java8-installer oracle-java8-set-default
